### ISSUE TITLE
Update on data?

### ISSUE THREAD

**Issue by smoothumut** [Zzz512/TSD#1]
Hi, first of all, thank you so much for the previous caries instance dataset, its code, and sharing it publicly. It is detailed and very helpful. 
I am looking forward to see the dataset with teeth and its parts segmentations which look beatiful. Hope it will pass the ethical review soon. Is there any update on that?
Many thanks in advance

**Comment by Zzz512** [comment]
Thank you for your interest in our new work, the work based on dental teeth structured instance segmentation has just been accepted, I believe the data is available in a few days.

**Comment by smoothumut** [comment]
Great to hear that 👍 
Thank you, for your quick reply and all the great work

**Comment by smoothumut** [comment]
Sorry to bother again, is there any update on data? 
Many thanks in advance

**Comment by Zzz512** [comment]
Sorry for the confusion. I believe I have provided our dataset download link.

**Comment by smoothumut** [comment]
ops, I am really sorry, My bad, I have missed it.
Thank you so much for sharing 🙇 
Have a great day

**Comment by Zzz512** [comment]
Never mind, have a good day
