### ISSUE TITLE
Inquiry about the dental anatomical structure annotation

### ISSUE THREAD

**Issue by taijizhao** [Zzz512/TSD#2]
Dear authors, first of all, congratulations on your awesome paper! I really appreciate you sharing the TSD dataset—it's been a great resource for me.
I'm particularly interested in the detection and segmentation of small/obscure/overlapping structures in medical images, and I think your dataset could be great helpful for this.
I've checked out the current version of the dataset, and I noticed it's got annotations for single tooth segmentation. I was wondering if you've got any plans to release annotations for anatomical structure segmentation too? And if you do, is there any idea when that might happen?
Thanks a ton for your time and for considering my question. I'm really looking forward to any updates you might have!
Cheers!

**Comment by Zzz512** [comment]
Dear Researcher,

I apologize for the confusion regarding your question about annotations for anatomical structure segmentation. If you are looking to obtain overlapping tooth structures, you can merge the instances of each image into a single mask for generating overlapping structures.

Best regards

**Comment by taijizhao** [comment]
> Dear Researcher,
> 
> I apologize for the confusion regarding your question about annotations for anatomical structure segmentation. If you are looking to obtain overlapping tooth structures, you can merge the instances of each image into a single mask for generating overlapping structures.
> 
> Best regards

Thank you for such quick response! I re-checked the annotation and realized that I misunderstood the dataset structure and made a mistake in parsing the json file. My problem is now solved. Thank you again for your help!
